version: '3'

services:

  selenium-hub:
    image: selenium/hub:latest
    expose:
      - 4444
    networks:
      - selenium-grid
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome-debug:latest
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - 5900:5900
    depends_on:
      - selenium-hub
    networks:
      - selenium-grid

networks:
  selenium-grid:

